spring: 
  datasource: 
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: platzi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true